### ISSUE TITLE
WP_Model class has some pending issues

### ISSUE THREAD

**Issue by VesterDe** [21stdigital/tfd-model#1]
Hey, you're depending on WP_Model, which has at least 1 bug you should be aware of.

https://github.com/anthonybudd/WP_Model/pull/10

You can fix that by using the pull_request fork version instead.

You'd need to change composer.json for that. Specifically:

`"repositories": [
    {
      "type": "vcs",
      "url": "http://github.com/simnom/WP_Model"
    }
  ],`

to take the forked repo, and then under require:

`"anthonybudd/wp_model": "dev-master",`

Gl.

EDIT: This goes for your tfd-image repository as well.

**Comment by JimSeven** [comment]
Hi @VesterDe,

thx for your hint! We changed the composer.json.

Best, 
Jim
